name: Bug Report
description: File a bug report
labels: ["bug"]
assignees:
  - tjhorner
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe the bug you encountered, and what you expected to happen instead.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please copy and paste any relevant log output. Learn how to obtain logs [here](https://upsy-desky.tjhorner.dev/docs/troubleshooting/#other-issues).
      render: plain text
  - type: input
    id: config-version
    attributes:
      label: Which version of the Upsy Desky firmware config are you running?
      placeholder: "1.1.1"
  - type: dropdown
    id: update-management
    attributes:
      label: How do you manage your Upsy Desky's updates?
      options:
        - OTA Updates
        - ESPHome YAML Config
  - type: input
    id: esphome-version
    attributes:
      label: If you're using an ESPHome YAML config, which version of ESPHome are you running?
      placeholder: "2023.5.4"
  - type: textarea
    id: esphome-config
    attributes:
      label: ESPHome Config
      description: If you have your own ESPHome YAML configuration, please paste it here. Remember to redact any sensitive information like encryption keys or passwords.
      render: YAML
