substitutions:
  name: "upsy-desky"

esphome:
  name: "${name}"
  name_add_mac_suffix: true
  project:
    name: tj_horner.upsy_desky
    version: "0.0.2"

esp32:
  board: esp32dev

logger:
  level: INFO

wifi:
  ap:
    password: "hunter2hunter2"

captive_portal:

improv_serial:

api:
  password: ""
  reboot_timeout: 0s

web_server:
  port: 80

ota:
  password: ""

packages:
  standing_desk: github://tjhorner/esphome-standing-desk/configs/template.yaml
  presets_addon: github://tjhorner/esphome-standing-desk/configs/addons/presets.yaml

light:
  - platform: status_led
    id: status
    pin: GPIO23
    restore_mode: ALWAYS_ON
