packages:
  base_config: !include _base.yaml

dashboard_import:
  package_import_url: github://tjhorner/upsy-desky/firmware/fully_jarvis.yaml

substitutions:
  standing_desk_uart_rx_pin: "17"
  standing_desk_up_pin: "21"
  standing_desk_down_pin: "22"
  standing_desk_variant: "jarvis"
  standing_desk_min_height: "24.5"
  standing_desk_max_height: "50.0"

  # Presets
  button_bit1_pin: "21"
  button_bit2_pin: "22"
  button_bit4_pin: "19"
  button_m_pin: "18"