name: Build Stock Firmware
on:
  release:
    types: [created]

jobs:
  build:
    name: Build Firmware
    runs-on: ubuntu-latest
    strategy:
      matrix:
        desk_brand:
          - uplift_v2
          - fully_jarvis
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install ESPHome
        run: pip install --user esphome
      
      - name: Compile Firmware
        working-directory: firmware
        run: |
          esphome compile ${{ matrix.desk_brand }}.yaml
          mkdir -p bin
          cp .esphome/build/upsy-desky/.pioenvs/upsy-desky/firmware-factory.bin bin/stock-${{ matrix.desk_brand }}.bin

      - name: Upload Firmware
        uses: skx/github-action-publish-binaries@release-1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "firmware/bin/*.bin"